# These are supported funding model platforms

github: @techfriends
patreon: https://www.patreon.com/c/TechFriends a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: https://github.com/Curiousgal/citrix-unified-workspace-api-native with Azure apps and Desktops
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: @Curiousgal add link
thanks_dev: Thank you! Azdev@techfriends.io # Replace with a single thanks.dev username
custom: Stripe
